/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wave_Zygote */

#ifndef _Included_com_wave_Zygote
#define _Included_com_wave_Zygote
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wave_Zygote
 * Method:    nativeForkSystemServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wave_Zygote_nativeForkSystemServer
  (JNIEnv *, jclass);

/*
 * Class:     com_wave_Zygote
 * Method:    nativeForkAndSpecialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wave_Zygote_nativeForkAndSpecialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
