/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wave_OS */

#ifndef _Included_com_wave_OS
#define _Included_com_wave_OS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wave_OS
 * Method:    nativePrctl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wave_OS_nativePrctl
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
