/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wave_FregService */

#ifndef _Included_com_wave_FregService
#define _Included_com_wave_FregService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wave_FregService
 * Method:    init_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wave_FregService_init_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_wave_FregService
 * Method:    setValue_native
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wave_FregService_setValue_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wave_FregService
 * Method:    getValue_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wave_FregService_getValue_1native
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
