/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_wave_FregService.h"
/*
 * Class:     com_wave_FregService
 * Method:    init_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wave_FregService_init_1native
  (JNIEnv *, jclass){

    printf("init freg\n");
    return 0;
}

/*
 * Class:     com_wave_FregService
 * Method:    setValue_native
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wave_FregService_setValue_1native
  (JNIEnv *, jclass, jint, jint){
    printf("setValue\n");

}

/*
 * Class:     com_wave_FregService
 * Method:    getValue_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wave_FregService_getValue_1native
  (JNIEnv *, jclass, jint){
    printf("getValue\n");
    return 0;
}


